<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edinburgh Airport Non-Aero API Documentation</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
    <style>
        body {
            font-family: 'Inter', sans-serif;
            background-color: #f8fafc; /* Tailwind gray-50 */
            color: #1f2937; /* Tailwind gray-800 */
        }
        .api-endpoint {
            border-left-width: 4px;
            padding-left: 1.5rem; /* pl-6 */
        }
        .api-get { border-color: #2563eb; /* Tailwind blue-600 */ }
        .api-post { border-color: #059669; /* Tailwind emerald-600 */ }
        .api-put { border-color: #d97706; /* Tailwind amber-600 */ }
        .api-delete { border-color: #dc2626; /* Tailwind red-600 */ }

        .method-badge {
            display: inline-block;
            padding: 0.25rem 0.75rem;
            border-radius: 0.375rem; /* rounded-md */
            font-weight: 600;
            text-transform: uppercase;
            font-size: 0.875rem; /* text-sm */
        }
        .method-get { background-color: #2563eb; color: white; }
        .method-post { background-color: #059669; color: white; }
        .method-put { background-color: #d97706; color: white; }
        .method-delete { background-color: #dc2626; color: white; }

        pre::-webkit-scrollbar {
            width: 8px;
            height: 8px;
        }
        pre::-webkit-scrollbar-track {
            background: #e5e7eb; /* gray-200 */
            border-radius: 10px;
        }
        pre::-webkit-scrollbar-thumb {
            background: #9ca3af; /* gray-400 */
            border-radius: 10px;
        }
        pre::-webkit-scrollbar-thumb:hover {
            background: #6b7280; /* gray-500 */
        }
        pre {
            max-height: 450px;
            background-color: #111827; /* Tailwind gray-900 */
            color: #f3f4f6; /* gray-100 */
            padding: 1rem;
            border-radius: 0.5rem; /* rounded-lg */
            overflow-x: auto;
        }
        code.inline-code {
            background-color: #e5e7eb; /* gray-200 */
            padding: 0.125rem 0.25rem;
            border-radius: 0.25rem; /* rounded-sm */
            color: #374151; /* gray-700 */
            font-size: 0.9em;
        }
        .resource-title {
            font-size: 1.75rem; /* text-2xl or similar */
            font-weight: 600; /* semibold */
            color: #111827; /* gray-900 */
            margin-bottom: 1.5rem; /* mb-6 */
            padding: 0.75rem; /* p-3 */
            background-color: #f3f4f6; /* gray-100 */
            border-radius: 0.5rem; /* rounded-lg */
        }
    </style>
</head>
<body class="text-gray-800">
    <div class="container mx-auto px-4 py-8 md:py-12">
        <header class="mb-12 text-center">
            <h1 class="text-4xl md:text-5xl font-bold text-gray-900 mb-4">Edinburgh Airport Non-Aero API</h1>
            <p class="text-lg text-gray-600">
                Access data related to passenger traffic, commercial revenue, and facility utilization at Edinburgh Airport.
            </p>
            <p class="mt-2 text-sm text-gray-500">
                Base URL: <code class="inline-code">https://api.edinburghairport.example.com/v1/non-aero</code>
            </p>
        </header>

        <section class="mb-8 mt-12">
            <h2 class="text-3xl font-bold text-gray-900 mb-10 text-center">API Endpoints</h2>
        </section>

        <section id="passenger-traffic-resource" class="mb-16">
            <h3 class="resource-title">Passenger Traffic & Terminal Operations</h3>
            <p class="text-gray-600 mb-8">Endpoints for accessing passenger movement and terminal activity data.</p>

            <div id="get-passenger-traffic" class="mb-10 p-6 bg-white rounded-xl shadow-lg api-endpoint api-get">
                <div class="flex items-center mb-4">
                    <span class="method-badge method-get mr-3">GET</span>
                    <h4 class="text-xl font-semibold text-gray-800">/passenger-traffic</h4>
                </div>
                <p class="text-gray-700 mb-4">Retrieves a list of passenger traffic records. Supports filtering by date, terminal, flight number, etc. (specific query parameters TBD).</p>
                <h5 class="font-medium text-gray-700 mt-6 mb-2">Example Success Response (200 OK):</h5>
                <pre><code class="language-json">[
  {
    "passenger_id": "P006",
    "flight_number": "VS101",
    "arrival_departure": "arrival",
    "terminal": "T1",
    "gate": "A08",
    "passenger_type": "international",
    "nationality": "US",
    "timestamp": "2024-01-15 13:20:00",
    "dwell_time_minutes": 75
  },
  {
    "passenger_id": "P007",
    "flight_number": "FR892",
    "arrival_departure": "departure",
    "terminal": "T1",
    "gate": "C15",
    "passenger_type": "international",
    "nationality": "ES",
    "timestamp": "2024-01-15 14:10:00",
    "dwell_time_minutes": 105
  }
  // ... more records
]</code></pre>
            </div>

            <div id="get-passenger-traffic-by-id" class="mb-10 p-6 bg-white rounded-xl shadow-lg api-endpoint api-get">
                <div class="flex items-center mb-4">
                    <span class="method-badge method-get mr-3">GET</span>
                    <h4 class="text-xl font-semibold text-gray-800">/passenger-traffic/{passengerId}</h4>
                </div>
                <p class="text-gray-700 mb-4">Retrieves a specific passenger traffic record by passenger ID.</p>
                <h5 class="font-medium text-gray-700 mt-6 mb-2">Path Parameters:</h5>
                <ul class="list-disc list-inside text-gray-700 mb-4">
                    <li><code class="inline-code">passengerId</code> (string, required): The unique identifier for the passenger record.</li>
                </ul>
                <h5 class="font-medium text-gray-700 mt-6 mb-2">Example Success Response (200 OK) for ID <code class="inline-code">P008</code>:</h5>
                <pre><code class="language-json">{
  "passenger_id": "P008",
  "flight_number": "BA445",
  "arrival_departure": "arrival",
  "terminal": "T1",
  "gate": "B09",
  "passenger_type": "domestic",
  "nationality": "UK",
  "timestamp": "2024-01-15 15:30:00",
  "dwell_time_minutes": 40
}</code></pre>
            </div>
             <div id="create-passenger-traffic" class="mb-10 p-6 bg-white rounded-xl shadow-lg api-endpoint api-post">
                <div class="flex items-center mb-4">
                    <span class="method-badge method-post mr-3">POST</span>
                    <h4 class="text-xl font-semibold text-gray-800">/passenger-traffic</h4>
                </div>
                <p class="text-gray-700 mb-4">Creates a new passenger traffic record. (Primarily for data ingestion, if applicable)</p>
                <h5 class="font-medium text-gray-700 mt-6 mb-2">Request Body (JSON):</h5>
                <pre><code class="language-json">{
  "flight_number": "NEWFLT",
  "arrival_departure": "departure",
  "terminal": "T1",
  "gate": "D01",
  "passenger_type": "international",
  "nationality": "CA",
  "timestamp": "2024-05-27 10:00:00",
  "dwell_time_minutes": 90
}</code></pre>
                <h5 class="font-medium text-gray-700 mt-6 mb-2">Example Success Response (201 Created):</h5>
                <pre><code class="language-json">{
  "passenger_id": "PNEW01", // Newly generated ID
  "flight_number": "NEWFLT",
  "arrival_departure": "departure",
  "terminal": "T1",
  "gate": "D01",
  "passenger_type": "international",
  "nationality": "CA",
  "timestamp": "2024-05-27 10:00:00",
  "dwell_time_minutes": 90
}</code></pre>
            </div>
            </section>

        <section id="commercial-revenue-resource" class="mb-16">
            <h3 class="resource-title">Commercial Revenue Streams</h3>
            <p class="text-gray-600 mb-8">Endpoints for accessing data on commercial transactions within the airport.</p>

            <div id="get-commercial-revenue" class="mb-10 p-6 bg-white rounded-xl shadow-lg api-endpoint api-get">
                <div class="flex items-center mb-4">
                    <span class="method-badge method-get mr-3">GET</span>
                    <h4 class="text-xl font-semibold text-gray-800">/commercial-revenue</h4>
                </div>
                <p class="text-gray-700 mb-4">Retrieves a list of commercial transactions. Supports filtering by vendor, product category, date range, etc.</p>
                <h5 class="font-medium text-gray-700 mt-6 mb-2">Example Success Response (200 OK):</h5>
                <pre><code class="language-json">[
  {
    "transaction_id": "T006",
    "passenger_id": "P006",
    "vendor_category": "retail",
    "vendor_name": "Boots",
    "product_category": "health_beauty",
    "amount_gbp": 18.95,
    "transaction_time": "2024-01-15 13:20:00",
    "location_zone": "main_terminal"
  },
  {
    "transaction_id": "T007",
    "passenger_id": "P007",
    "vendor_category": "food_beverage",
    "vendor_name": "Burger King",
    "product_category": "fast_food",
    "amount_gbp": 14.50,
    "transaction_time": "2024-01-15 14:15:00",
    "location_zone": "departure_lounge"
  }
  // ... more records
]</code></pre>
            </div>

            <div id="get-commercial-revenue-by-id" class="mb-10 p-6 bg-white rounded-xl shadow-lg api-endpoint api-get">
                <div class="flex items-center mb-4">
                    <span class="method-badge method-get mr-3">GET</span>
                    <h4 class="text-xl font-semibold text-gray-800">/commercial-revenue/{transactionId}</h4>
                </div>
                <p class="text-gray-700 mb-4">Retrieves a specific commercial transaction by its ID.</p>
                 <h5 class="font-medium text-gray-700 mt-6 mb-2">Path Parameters:</h5>
                <ul class="list-disc list-inside text-gray-700 mb-4">
                    <li><code class="inline-code">transactionId</code> (string, required): The unique identifier for the transaction.</li>
                </ul>
                <h5 class="font-medium text-gray-700 mt-6 mb-2">Example Success Response (200 OK) for ID <code class="inline-code">T008</code>:</h5>
                <pre><code class="language-json">{
  "transaction_id": "T008",
  "passenger_id": "P008",
  "vendor_category": "duty_free",
  "vendor_name": "World Duty Free",
  "product_category": "perfume_cosmetics",
  "amount_gbp": 67.80,
  "transaction_time": "2024-01-15 15:45:00",
  "location_zone": "international_departure"
}</code></pre>
            </div>
            </section>

        <section id="facilities-resource" class="mb-16">
            <h3 class="resource-title">Facility Utilization & Services</h3>
            <p class="text-gray-600 mb-8">Endpoints for data on airport facilities, their utilization, and status.</p>

            <div id="get-facilities" class="mb-10 p-6 bg-white rounded-xl shadow-lg api-endpoint api-get">
                <div class="flex items-center mb-4">
                    <span class="method-badge method-get mr-3">GET</span>
                    <h4 class="text-xl font-semibold text-gray-800">/facilities</h4>
                </div>
                <p class="text-gray-700 mb-4">Retrieves a list of airport facilities and their current status. Supports filtering by facility type, zone, maintenance status, etc.</p>
                <h5 class="font-medium text-gray-700 mt-6 mb-2">Example Success Response (200 OK):</h5>
                <pre><code class="language-json">[
  {
    "facility_id": "F006",
    "facility_type": "retail_unit",
    "zone": "main_terminal",
    "capacity": 45,
    "current_occupancy": 32,
    "revenue_per_hour": 175.00,
    "operating_hours": "06:00-22:00",
    "maintenance_status": "operational"
  },
  {
    "facility_id": "F007",
    "facility_type": "restaurant",
    "zone": "departure_lounge",
    "capacity": 120,
    "current_occupancy": 95,
    "revenue_per_hour": 220.00,
    "operating_hours": "05:00-23:00",
    "maintenance_status": "operational"
  },
  {
    "facility_id": "F008",
    "facility_type": "parking_space",
    "zone": "car_park_2",
    "capacity": 300,
    "current_occupancy": 245,
    "revenue_per_hour": 4.25,
    "operating_hours": "24/7",
    "maintenance_status": "operational"
  }
  // ... more records
]</code></pre>
            </div>

            <div id="get-facility-by-id" class="mb-10 p-6 bg-white rounded-xl shadow-lg api-endpoint api-get">
                <div class="flex items-center mb-4">
                    <span class="method-badge method-get mr-3">GET</span>
                    <h4 class="text-xl font-semibold text-gray-800">/facilities/{facilityId}</h4>
                </div>
                <p class="text-gray-700 mb-4">Retrieves details for a specific facility by its ID.</p>
                 <h5 class="font-medium text-gray-700 mt-6 mb-2">Path Parameters:</h5>
                <ul class="list-disc list-inside text-gray-700 mb-4">
                    <li><code class="inline-code">facilityId</code> (string, required): The unique identifier for the facility.</li>
                </ul>
                <h5 class="font-medium text-gray-700 mt-6 mb-2">Example Success Response (200 OK) for ID <code class="inline-code">F009</code>:</h5>
                <pre><code class="language-json">{
  "facility_id": "F009",
  "facility_type": "advertising_board",
  "zone": "main_terminal",
  "capacity": 1,
  "current_occupancy": 1,
  "revenue_per_hour": 30.00,
  "operating_hours": "24/7",
  "maintenance_status": "maintenance_required"
}</code></pre>
            </div>

            <div id="create-facility" class="mb-10 p-6 bg-white rounded-xl shadow-lg api-endpoint api-post">
                <div class="flex items-center mb-4">
                    <span class="method-badge method-post mr-3">POST</span>
                    <h4 class="text-xl font-semibold text-gray-800">/facilities</h4>
                </div>
                <p class="text-gray-700 mb-4">Creates a new facility record (e.g., for internal airport management systems).</p>
                <h5 class="font-medium text-gray-700 mt-6 mb-2">Request Body (JSON):</h5>
                <pre><code class="language-json">{
  "facility_type": "lounge",
  "zone": "international_departure_ext",
  "capacity": 75,
  "current_occupancy": 10,
  "revenue_per_hour": 60.00,
  "operating_hours": "05:00-23:00",
  "maintenance_status": "operational"
}</code></pre>
                <h5 class="font-medium text-gray-700 mt-6 mb-2">Example Success Response (201 Created):</h5>
                <pre><code class="language-json">{
  "facility_id": "FNEW01", // Newly generated ID
  "facility_type": "lounge",
  "zone": "international_departure_ext",
  "capacity": 75,
  "current_occupancy": 10,
  "revenue_per_hour": 60.00,
  "operating_hours": "05:00-23:00",
  "maintenance_status": "operational",
  "createdAt": "2024-05-27T10:00:00Z"
}</code></pre>
            </div>

            <div id="update-facility" class="mb-10 p-6 bg-white rounded-xl shadow-lg api-endpoint api-put">
                <div class="flex items-center mb-4">
                    <span class="method-badge method-put mr-3">PUT</span>
                    <h4 class="text-xl font-semibold text-gray-800">/facilities/{facilityId}</h4>
                </div>
                <p class="text-gray-700 mb-4">Updates an existing facility's details. Send only the fields to be updated.</p>
                 <h5 class="font-medium text-gray-700 mt-6 mb-2">Request Body (JSON) for ID <code class="inline-code">F009</code>:</h5>
                <pre><code class="language-json">{
  "maintenance_status": "operational",
  "revenue_per_hour": 35.00
}</code></pre>
                <h5 class="font-medium text-gray-700 mt-6 mb-2">Example Success Response (200 OK):</h5>
                <pre><code class="language-json">{
  "facility_id": "F009",
  "facility_type": "advertising_board",
  "zone": "main_terminal",
  "capacity": 1,
  "current_occupancy": 1,
  "revenue_per_hour": 35.00, // Updated
  "operating_hours": "24/7",
  "maintenance_status": "operational", // Updated
  "updatedAt": "2024-05-27T11:00:00Z"
}</code></pre>
            </div>

            <div id="delete-facility" class="mb-10 p-6 bg-white rounded-xl shadow-lg api-endpoint api-delete">
                <div class="flex items-center mb-4">
                    <span class="method-badge method-delete mr-3">DELETE</span>
                    <h4 class="text-xl font-semibold text-gray-800">/facilities/{facilityId}</h4>
                </div>
                <p class="text-gray-700 mb-4">Decommissions or removes a facility record.</p>
                <h5 class="font-medium text-gray-700 mt-6 mb-2">Example Success Response (204 No Content):</h5>
                <p class="text-gray-600 italic">(No body content is returned)</p>
            </div>
        </section>

        <footer class="mt-16 pt-8 border-t border-gray-300 text-center">
            <p class="text-gray-600">&copy; <span id="currentYear"></span> Edinburgh Airport (Example). All rights reserved.</p>
            <p class="text-sm text-gray-500 mt-1">API Documentation Template</p>
        </footer>
    </div>

    <script>
        // Set the current year in the footer
        document.getElementById('currentYear').textContent = new Date().getFullYear();
    </script>
</body>
</html>
